language: python

python:
  - "2.7"

install:
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin python-gdal
  - pip install GDAL

script:
  - ogrinfo --version
  - ogrinfo wmo-ra.geojson
  - python validate.py wmo-ra.geojson
