language: c

install:
  - sudo apt-get update
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin python-gdal

script:
  - ogrinfo wmo-ra.geojson
  - python validate.py wmo-ra.geojson
