language: c

install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin python-gdal

script:
  - ogrinfo wmo-ra.geojson
  - python validate.py wmo-ra.geojson
